---
# File: setup_mac.yml
# Main playbook - updated to load multiple variable files

# Ensure community.general collection is installed
- name: Bootstrap required Ansible collections
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install community.general collection (always runs, but idempotent)
      ansible.builtin.command: ansible-galaxy collection install community.general --force
      changed_when: true 

- name: Set up Mac with Homebrew Packages/Casks, 1Password, chezmoi, and dotfiles
  hosts: localhost
  connection: local
  become: false
  gather_facts: true

  vars_files:
    - vars/main.yml          # Core variables (1Password, chezmoi repo)
    - vars/brew_packages.yml # Homebrew packages
    - vars/brew_casks.yml    # Homebrew casks

  pre_tasks:
    - name: Ensure Ansible is installed via Homebrew
      community.general.homebrew:
        name: ansible
        state: present

  roles:
    - homebrew
    - 1Password
    - chezmoi